# Load libraries
library(janitor)
#library(corrplot)
library(tidyverse)
library(dplyr)
library(Hmisc)
library(broom)
library(qgcomp)
library(rjags)
library(LUCIDus)
library(plotly)
library(gWQS)
library(flextable)
library(magrittr)
library(summarytools)
# install.packages("bkmr")
library(bkmr)
library(survival)
#install.packages("usethis")
#library(usethis)
#usethis::edit_r_environ()
#install.packages("devtools")
#library(devtools)
#install_github("jokergoo/ComplexHeatmap")
library(ComplexHeatmap)
#install_github("JAGoodrich/jag2")
library(jag2)
library(gtsummary)
library(lme4)
library(tools)
library(broom)
#install.packages("clusterGeneration")
library(clusterGeneration)
#Sys.setenv(GITHUB_PAT = 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) 
#install_github("ElenaColicino/bwqs", build_vignettes = TRUE)
library(BWQS)
library(gWQS)
library(cowplot)
library(gt)

