---
title: 'STRIVE'
subtitle: "Final Analysis"
author: "Hongxu Wang"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
editor_options: 
  chunk_output_type: console
---
```{r setup univariate analysis cat pfas, include=FALSE, echo=FALSE}
options(knitr.table.format = "html")
knitr::opts_chunk$set(echo = TRUE,warning=FALSE, message = FALSE, cache=FALSE,collapse=FALSE)

source(fs::path(here::here("!libraries.R")))
source(fs::path(here::here("!directories.R")))
# source(fs::path(here::here("functions.R")))
source(fs::path(here::here("!load_data.R")))
```

## Analysis1. Logistic regression 
**Outcome: case vs control**

**Exposure: normalized pfas**

**Covars: source, age, sex, race/eth, rural, smoking**

**Analysis: logistic regression**

```{r analysis}
res <- epiomics::owas(data_scaled,
                          var = "case_control", 
                          omics = pfas_name_scld,
                          covars = covars,
                          var_exposure_or_outcome = "outcome",
                          family = "binomial",
                          conf_int = TRUE,
                          ref_group = "Healthy") %>%
  mutate(odds_ratio = exp(estimate),
         exp_ci_low = exp(conf_low),
         exp_ci_high = exp(conf_high))

# reorder PFAS by estimate
res1 <- res |> 
  mutate(sig = case_when((p_value < 0.05 & adjusted_pval < 0.05) ~
                           "Sig.(FDR < 0.05)",
                          p_value < 0.05 ~ "Sig.(p value < 0.05)", 
                         p_value >= 0.05 ~ "Not Sig.")) %>%
  mutate(plot_name = case_when(grepl("pfba", feature_name) ~ "PFBA",
                               grepl("pf_hp_a", feature_name) ~ "PFHpA",
                               grepl("pf_pe_s", feature_name) ~ "PFPeS",
                               grepl("pfbs", feature_name) ~ "PFBS",
                               grepl("pf_hx_a", feature_name) ~ "PFHxA",
                               grepl("pf_do_a", feature_name) ~ "PFDoA",
                               grepl("pfda", feature_name) ~ "PFDA",
                               grepl("pf_pe_a", feature_name) ~ "PFPeA",
                               grepl("pf_un_a", feature_name) ~ "PFUnA",
                               grepl("pfna", feature_name) ~ "PFNA",
                               grepl("pfos", feature_name) ~ "PFOS",
                               grepl("pf_hx_s", feature_name) ~ "PFHxS",
                               grepl("pf_hp_s", feature_name) ~ "PFHpS",
                               grepl("pfoa", feature_name) ~ "PFOA",
                               grepl("pf3ons", feature_name) ~ "9CL-PF3ONS",))

writexl::write_xlsx(res1,
                    fs::path(dir_result,
                             "exposure outcome association.xlsx"))
```

## Fig. PFAS and outcome
```{r plot}
(plot <-  ggplot(res1,
       aes(x = odds_ratio, y = fct_reorder(plot_name, odds_ratio), color = sig)) +
  geom_errorbar(aes(xmin = exp_ci_low, xmax = exp_ci_high),
                width = 0, position = position_dodge(width = 1)) +
  geom_point(size = 1, position = position_dodge(width = 1)) + 
  geom_vline(xintercept = 1, linetype = 2, color = "grey") +
  xlab("Odds Ratio (95% CI)") +
  theme(
        legend.position = "bottom",
        panel.background = element_rect(fill="white"), 
        strip.background = element_rect(fill = "white"),
        strip.text.y = element_text(angle = 0, hjust = 0),
        text = element_text(size = 15),
        axis.title.y = element_blank(),
        axis.line.x = element_line(color = "black"),
        axis.line.y = element_line(color = "black")) +
  ylab("OR (95% CI) per\ndoubling of PFAS") +
  # scale_color_manual(values = c( "black","purple","red")))
  scale_color_manual(values = c( "black","red")))

ggsave(filename = fs::path(dir_figures,
                           "Fig1. PFAS main Effect with covariates Imputed.jpeg"),
       width = 8,
       height = 8,
       dpi = 300,
       bg = "white")
```

